# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This is a sample saved layout file for testing. It is not intended to be
# used in production.

[Window][Scene]
Pos=0,24
Size=239,545
Collapsed=0
DockId=0x00000005,0

[Window][Details]
Pos=962,24
Size=321,791
Collapsed=0
DockId=0x00000002,0

[Window][WindowOverViewport_11111111]
Pos=0,24
Size=1283,791
Collapsed=0

[Window][Debug##Default]
Pos=60,60
Size=400,400
Collapsed=0

[Window][Toolbar]
Pos=557,24
Size=168,46
Collapsed=0

[Window][Console]
Pos=0,571
Size=960,244
Collapsed=0
DockId=0x00000004,0

[Window][Asset Library]
Pos=0,571
Size=960,244
Collapsed=0
DockId=0x00000004,1

[Docking][Data]
DockSpace       ID=0x38E8C8C8 Window=0xA87D555D Pos=0,24 Size=1283,791 Split=X
  DockNode      ID=0x00000001 Parent=0x38E8C8C8 SizeRef=960,815 Split=Y
    DockNode    ID=0x00000003 Parent=0x00000001 SizeRef=960,569 Split=X
      DockNode  ID=0x00000005 Parent=0x00000003 SizeRef=239,569 Selected=0xE192E354
      DockNode  ID=0x00000006 Parent=0x00000003 SizeRef=719,569 CentralNode=1
    DockNode    ID=0x00000004 Parent=0x00000001 SizeRef=960,244 Selected=0x49278EEE
  DockNode      ID=0x00000002 Parent=0x38E8C8C8 SizeRef=321,815 Selected=0xFC3EA205

