// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package imp.gltf;

import "core/math/math.proto";
import "core/proto/imp.proto";

// option cc_api_version = 2;
option java_package = "com.google.ar.imp.proto";

message Interactivity {
  message Graph {
    enum ValueType {
      UNKNOWN = 0;
      BOOL = 1;
      INT = 2;
      FLOAT = 3;
      FLOAT2 = 4;
      FLOAT3 = 5;
      FLOAT4 = 6;
      MAT2F = 7;
      MAT3F = 8;
      MAT4F = 9;
      STRING = 10;
    }

    // TODO  Add the rest of the data types defined in the glTF
    // object model spec + behavior spec.
    message Variable {
      string id = 1;
      ValueType type = 2;
      oneof value {
        bool value_bool = 3;
        sint32 value_int = 4;
        float value_float = 5;
        Float2 value_float2 = 6;
        Float3 value_float3 = 7;
        Float4 value_float4 = 8;
        Mat2f value_mat2f = 9;
        Mat3f value_mat3f = 10;
        Mat4f value_mat4f = 11;
        string value_string = 12;
      }
    }

    message Declaration {
      // TODO : Add support for declaring custom nodes.
      // https://github.com/KhronosGroup/glTF/blob/interactivity/extensions/2.0/Khronos/KHR_interactivity/Specification.adoc#55-declarations
      string op = 1;
    }

    message Node {
      // TODO: Remove unused configuration types.
      enum ConfigurationType {
        UNKNOWN = 0;
        VARIABLE = 1;
        NUMBER_OF_OUTPUT_FLOWS = 2;
        POINTER = 3;
        EVENT = 4;
        NODE_INDEX = 5;
        STOP_PROPAGATION = 6;
        EASING_TYPE = 7;
        EASING_DURATION = 8;
        CASES = 9;
        TYPE = 10;
        NUMBER_OF_INPUT_FLOWS = 11;
        IS_RANDOM = 12;
        IS_LOOP = 13;
        MESSAGE = 14;
        INITIAL_INDEX = 15;
        VARIABLES = 16;
        USE_SLERP = 17;
        SEVERITY = 18;
      }

      message Flow {
        optional uint32 node = 1;
        string socket = 2;
      }

      message Configuration {
        message IntArray {
          repeated int32 values = 1;
        }

        ConfigurationType id = 1;
        oneof value {
          sint32 value_int = 2;
          string value_string = 3;
          bool value_bool = 4;
          float value_float = 5;
          IntArray value_int_array = 6;
        }
      }

      message Value {
        oneof value {
          Variable variable = 1;
          Flow connection = 2;
        }
      }

      uint32 declaration = 1;
      map<string, Configuration> configuration = 2;
      map<string, Value> values = 3;
      map<string, Flow> flows = 4;
    }

    message Event {
      string id = 1;
      map<string, Variable> values = 2;
    }

    message Type {
      string signature = 1;
    }

    repeated Node nodes = 1;
    repeated Variable variables = 2;
    repeated Event events = 3;
    repeated Type types = 4;
    repeated Declaration declarations = 5;
  }

  repeated Graph graphs = 1;
  uint32 graph = 2;
}
