# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Helper functions for using assets with the Impress Framework."""

load("@com_google_impress//core/resources:resources.bzl", "imp_resources")

def imp_assets_base_url():
    return select({
        "@third_party//filament:android": "https://www.gstatic.com/ar/core/viewer/android",
        "@third_party//filament:filament_uses_opengl_ios": "https://www.gstatic.com/ar/core/viewer/ios_gles3",
        "@third_party//filament:filament_uses_metal_ios": "https://www.gstatic.com/ar/core/viewer/ios_metal",
        "@third_party//filament:ios": "https://www.gstatic.com/ar/core/viewer/ios_metal",
        
        "@com_google_impress//core:ios_simulator_linux_metal": "https://www.gstatic.com/ar/core/viewer/ios_metal",
        
        "@third_party//filament:filament_uses_opengl_ios_x86_64": "https://www.gstatic.com/ar/core/viewer/ios_gles3",
        "@third_party//filament:filament_uses_metal_ios_x86_64": "https://www.gstatic.com/ar/core/viewer/ios_metal",
        "//conditions:default": "",
    })

def imp_assets(
        name,
        srcs = [],
        namespace = "",
        base_url = "",
        urls = {},
        embed = True,
        **kwargs):
    """Defines a set of imp assets.

    Generates a header that defines constants for a set of assets that are
    used to load assets at runtime through the AssetManager.

    The assets are either embedded into the binary or downloaded depending on if the
    [embed] attribute is true. It is recommended to create a build-time switch (i.e.
    through a config_setting) to control if assets are embedded or downloaded. This
    allows assets to be downloaded in production builds but embedded in development
    builds for rapid iteration.

    For an example usage, see the following files:
      @com_google_impress//samples/simple/BUILD
      @com_google_impress//samples/simple/simple_view.cc

    Registering Assets:
        Assets must be registered before they can be loaded.

        Assets are automatically registered when passed into the AssetManager.

        However, they must be registered explicitly to load them by their string
        identifier. For example, when referencing a resource by string in a .isf
        file.

        To explicitly register assets, call the function
        foo_assets::RegisterPathToFoo() generated by the imp_assets rule.

        Registering the assets makes it possible to reference a resource by
        nothing but its string identifier and have it automatically switch between
        loading an embedded version of an asset and a remote version of an asset
        based on if the imp_assets were embedded in a build.

    See:
      third_party/impress/core/resources/resource_embedded_h.tmpl

    Outputs:
        A cc_library named <name> exporting a header file named <name>.h which defines
        constants corresponding to each entry of srcs called <namespace>::k<SrcFile>

    Args:
        name: The target name used to depend on these asset.
        namespace: The namespace in which the asset constants will be defined.
        srcs: The list of asset files which should be embedded. Must be locations
          under the current directory in google3.
        base_url: The base network url at which the given resource files can be
          loaded based on their relative paths in google3 or based on the urls map.
        urls: Map of file labels to URLs.  If no URL is specified for a label, the
          URL will be derived from the path.
        embed: If true (default), embeds assets into the binary. Otherwise, download assets based on the
          base_url and urls attributes.
        **kwargs: Additional args passed through to the underlying imp_resources rule (i.e. visibility).
    """

    imp_resources(
        name = name,
        out_header = name + ".h",
        srcs = srcs,
        namespace = namespace,
        base_url = base_url,
        urls = urls,
        embed = embed,
        **kwargs
    )
