"""Generated by generate_static_assets.sh; do not edit."""

GSTATIC_URL_LOOKUP = {}

GSTATIC_URL_LOOKUP["ios_gles3"] = {}
GSTATIC_URL_LOOKUP["ios_metal"] = {}
GSTATIC_URL_LOOKUP["android"] = {}

GSTATIC_URL_LOOKUP["ios_gles3"]["compiled_imp_default_gltf_materials"] = "https://www.gstatic.com/impress/ios_gles3/compiled_imp_default_gltf_materials/f57c9da375d39b0d8695370b32b907b5.zip"
GSTATIC_URL_LOOKUP["ios_gles3"]["compiled_imp_default_lite_gltf_materials"] = "https://www.gstatic.com/impress/ios_gles3/compiled_imp_default_lite_gltf_materials/f9945226c21ed193545b7d6702da09e5.zip"
GSTATIC_URL_LOOKUP["ios_metal"]["compiled_imp_default_gltf_materials"] = "https://www.gstatic.com/impress/ios_metal/compiled_imp_default_gltf_materials/7482d6ff867827797adccdac3cb32384.zip"
GSTATIC_URL_LOOKUP["ios_metal"]["compiled_imp_default_lite_gltf_materials"] = "https://www.gstatic.com/impress/ios_metal/compiled_imp_default_lite_gltf_materials/4f646ed5431e20642a4343ee2de18688.zip"
GSTATIC_URL_LOOKUP["android"]["compiled_imp_default_gltf_materials"] = "https://www.gstatic.com/impress/android/compiled_imp_default_gltf_materials/ca6fbaa6092be008d6da15e7986665ac.zip"
GSTATIC_URL_LOOKUP["android"]["compiled_imp_default_lite_gltf_materials"] = "https://www.gstatic.com/impress/android/compiled_imp_default_lite_gltf_materials/9060e2f1be6051b529114b4edcc50964.zip"
