"""Generated by generate_static_assets.sh; do not edit."""

GSTATIC_URL_LOOKUP = {}

GSTATIC_URL_LOOKUP["ios_gles3"] = {}
GSTATIC_URL_LOOKUP["ios_metal"] = {}
GSTATIC_URL_LOOKUP["android"] = {}

GSTATIC_URL_LOOKUP["ios_gles3"]["compiled_imp_default_gltf_materials"] = "https://www.gstatic.com/impress/ios_gles3/compiled_imp_default_gltf_materials/591751784008c4e8cd4e6e571994b928.zip"
GSTATIC_URL_LOOKUP["ios_gles3"]["compiled_imp_default_lite_gltf_materials"] = "https://www.gstatic.com/impress/ios_gles3/compiled_imp_default_lite_gltf_materials/a1da03399d518f8c4d2878b8068cd8b5.zip"
GSTATIC_URL_LOOKUP["ios_metal"]["compiled_imp_default_gltf_materials"] = "https://www.gstatic.com/impress/ios_metal/compiled_imp_default_gltf_materials/26bf82c4df69eab7bde7b29645151980.zip"
GSTATIC_URL_LOOKUP["ios_metal"]["compiled_imp_default_lite_gltf_materials"] = "https://www.gstatic.com/impress/ios_metal/compiled_imp_default_lite_gltf_materials/0feeb385d0cc6e89997fc519e5f04ed5.zip"
GSTATIC_URL_LOOKUP["android"]["compiled_imp_default_gltf_materials"] = "https://www.gstatic.com/impress/android/compiled_imp_default_gltf_materials/4f3b425a262c89a138c73fd09176d041.zip"
GSTATIC_URL_LOOKUP["android"]["compiled_imp_default_lite_gltf_materials"] = "https://www.gstatic.com/impress/android/compiled_imp_default_lite_gltf_materials/609eb7a03a271b7b06a52445b9e47ff4.zip"
