// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package imp;

// Component for running intersection tests against the Text Renderer.
// Next ID: 3
message TextColliderState {
  // Ratio indicating how much to pad the real bounds of the text when doing
  // intersection tests. For example, if this is set to 0.1, then the size of
  // the bounds will be expanded by 10% for intersection tests.
  // It is assumed padding ratio is always greater than -1.0f.
  float padding_ratio = 1;
}
