# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("//build_tools:imp_material.bzl", "imp_material")

package(default_visibility = ["//visibility:public"])

imp_material(
    name = "debug_uv0",
    src = "debug_uv0.mat",
)

imp_material(
    name = "debug_uv1",
    src = "debug_uv1.mat",
)

imp_material(
    name = "debug_color",
    src = "debug_color.mat",
)

imp_material(
    name = "debug_normal",
    src = "debug_normal.mat",
)

imp_material(
    name = "debug_bone_indices",
    src = "debug_bone_indices.mat",
)

imp_material(
    name = "debug_bone_weights",
    src = "debug_bone_weights.mat",
)
