// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

include "core/loader/provider/schemas/loaded_model.fbs";
namespace imp.loader.ipc.schemas;

//
// Client->Service requests.
//

table Start {
  // The source Uri, used to determine the basename when requesting additional
  // resources.
  uri: string;
  // File contents.
  data: [uint8];
  // Specifies if the glTF is being loaded using lite materials.
  use_lite_materials: bool;
  // Specifies if the glTF being loaded should exclude excess nodes that don't
  // impact how the glTF is visually rendered.
  exclude_excess_nodes: bool;
  // Specifies if the glTF being loaded should have its baked shadow planes
  // removed if there's any.
  remove_shadow_planes: bool;
}

table TryLoad {
}

table AddResource {
  // Whether or not this was a missing resource, if this is true and the
  // resource wasn't returned as a missing resource path, this will result in an
  // errror.
  was_missing: bool;
  // Resource path or Uri.
  path: string;
  // File contents.
  data: [uint8];
}

table GetLoadedModel { }

table Done { }

union RequestTypes {
  Start,
  TryLoad,
  AddResource,
  GetLoadedModel,
  Done,
}

table Request {
  request: RequestTypes;
}

root_type Request;

//
// Service->Client responses.
//

table ErrorResponse {
  message: string;
}

table StartResponse { }

table TryLoadResponse {
  missing_resource_paths: [string];
  loaded: bool;
}

table AddResourceResponse { }

table GetLoadedModelResponse {
  buffer:[uint8] (required, nested_flatbuffer: "imp.schemas.LoadedModel");
}

table DoneResponse {
  protos_pushed: int32;
}

union ResponseTypes {
  ErrorResponse,
  StartResponse,
  TryLoadResponse,
  AddResourceResponse,
  GetLoadedModelResponse,
  DoneResponse,
}

// Service->Client responses.
table Response {
  response: ResponseTypes;
}

root_type Response;
