/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

syntax = "proto3";

package imp;

import "core/math/math.proto";
import "core/proto/imp.proto";

// Configuration information that describes how a type of particle should be
// created and emitted by a ParticleEmitter.
// Next ID: 7
message ParticleConfig {
  // The length of time, in seconds, that a particle will remain active.
  optional float lifetime_in_seconds = 1;

  // If true, the particle will orient itself to always face the camera.
  optional bool billboard = 2;

  // The base alpha value to apply to the particle. This only applies to
  // particles that consist of a color, or a texture with an alpha channel.
  optional float alpha = 3;

  // The base scale value to apply to the particle. Like alpha, this value is
  // used as a base value that can be modified by an optional scale_curve.
  optional float scale = 4;

  // The initial velocity of the particle.
  Float3 velocity = 5 [(optional_type) = ABSL_OPTIONAL];

  // A constant acceleration to apply to the particle velocity over time.
  // Common examples are gravity and convection.
  Float3 acceleration = 6 [(optional_type) = ABSL_OPTIONAL];
}
