/*
 * Copyright 2025 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

edition = "2024";

package imp;

import "core/math/math.proto";
import "core/proto/imp.proto";

// Configuration information that describes how a type of particle should be
// created and emitted by a ParticleEmitter.
// Next ID: 9
message ParticleConfig {
  // Rotation of the particle
  Quatf initial_rotation = 1 [(imp.msg_default) = "{0.0f, 0.0f, 0.0f, 1.0f}"];

  // Size of the particle.
  Float3 initial_scale = 2 [(imp.msg_default) = "{1.0f, 1.0f, 1.0f}"];

  // The gltf asset to use as the visual representation of the particle.
  // This field is required for emitters configured with the
  // PARTICLE_RENDERER_NODE renderer.
  string gltf_asset = 3 [default = ""];

  // The length of time, in seconds, that a particle will remain active.
  float lifetime_in_seconds = 4 [default = 1.0];

  // If true, particles will orient themselves to always face the camera.
  bool billboard = 5 [default = false];

  // The base alpha value to apply to the particle. This only applies to
  // particles that consist of a color, or a texture with an alpha channel.
  float initial_alpha = 6 [default = 1.0];

  // The initial velocity of the particle.
  Float3 initial_velocity = 7 [(imp.msg_default) = "{0.0f, 0.0f, 0.0f}"];

  // A constant acceleration to apply to the particle velocity over time.
  // Common examples are gravity and convection.
  Float3 acceleration = 8 [(imp.msg_default) = "{0.0f, 0.0f, 0.0f}"];
}

// Configuration information that describes how an emitter should behave.
// Next ID: 5
message EmitterConfig {
  // The length of time, in seconds, that the emitter should remain active.
  // Must not be negative.
  float duration_in_seconds = 1 [default = 0.0];

  // Indicates the emitter will restart after the duration has elapased?
  bool loop = 2 [default = false];

  // The maximum number of particles that may be active at any given time.
  // This value must be greater than 0 or no particles will be emitted.
  int32 max_particles = 3 [default = 1];

  // Number of particles to emit (on average) per second.
  float particles_per_second = 4 [default = 1.0];
}

// Configuration information that describes how particles should be created and
// by a ParticleEmitter.
// Next ID: 4
message ParticleEmitterState {
  // Definition of the different rendering pathways available for particles.
  enum ParticleRenderer {
    // Billboard and static mesh particles be fully owned by the emitter.
    // Will using Filament's instancing API to render copies of the particles.
    PARTICLE_RENDERER_DRAW_DEFAULT = 0;

    // Node particles will be rendered by their assigned MeshRenderer. The
    // emitter will update the state on the node directly each frame.
    PARTICLE_RENDERER_NODE = 1;
  }

  // Defines how the particles will be rendered, see the ParticleRenderer
  // definition above for more details.
  ParticleRenderer renderer = 1 [default = PARTICLE_RENDERER_DRAW_DEFAULT];

  // Configuration for how the emitter should behave.
  EmitterConfig emitter_config = 2;

  // Configuration for the particle to emit.
  ParticleConfig particle_config = 3;
}
