/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef THIRD_PARTY_IMPRESS_CORE_SPLIT_ENGINE_ANDROID_SPLIT_ENGINE_SHARED_MEMORY_BRIDGE_SERVICE_H_
#define THIRD_PARTY_IMPRESS_CORE_SPLIT_ENGINE_ANDROID_SPLIT_ENGINE_SHARED_MEMORY_BRIDGE_SERVICE_H_

#include <aidl/imp/split_engine/BnSplitEngineSharedMemoryBridge.h>
#include <aidl/imp/split_engine/BnSplitEngineToken.h>
#include <android/native_window_aidl.h>

#include <cstdint>
#include <memory>
#include <vector>

#include "aidl/imp/split_engine/ISplitEngineResponseHandler.h"
#include "aidl/imp/split_engine/ISplitEngineSharedMemoryReverseBridge.h"
#include "core/async/executor.h"
#include "core/split_engine/android/aidl/split_engine_shared_memory_bridge_service_aidl_ndk_lib_aidl_code_gen/aidl/imp/split_engine/ISplitEngineResponseHandler.h"
#include "core/split_engine/android/split_engine_shared_memory_bridge_service_impl.h"
#include "core/view/base_view.h"

namespace imp::split_engine {

/**
 * Implementation of an ISplitEngineSharedMemoryBridge service. This service
 * provides shared memory buffer management and processing for Impress
 * split engine.
 */
class SplitEngineSharedMemoryBridgeService
    : public aidl::imp::split_engine::BnSplitEngineSharedMemoryBridge {
 public:
  SplitEngineSharedMemoryBridgeService(BaseView& view, Executor* executor);
  void Update(BaseView& view, Executor* executor);

  // Start AIDL implementation.
  //
  // These functions are implementations of the AIDL
  // BnSplitEngineSharedMemoryBridge class. This code is autogenerated, and
  // uses a different naming convention than standard C++ code.
  ndk::ScopedAStatus initializeBridge(
      const std::shared_ptr<
          ::aidl::imp::split_engine::ISplitEngineSharedMemoryReverseBridge>&
          in_reverse_bridge,
      ::ndk::SpAIBinder* out_bridge_handle) override;
  ndk::ScopedAStatus registerBuffer(
      const ::ndk::SpAIBinder& in_bridge_handle,
      const ::ndk::ScopedFileDescriptor& in_file_descriptor,
      int32_t in_size_bytes, ::ndk::SpAIBinder* out_buffer_handle) override;
  ndk::ScopedAStatus processRegion(const ::ndk::SpAIBinder& in_buffer_handle,
                                   int32_t in_offset_bytes,
                                   int32_t in_region_length_bytes) override;

  ndk::ScopedAStatus createExternalTextureSurface(
      const ::ndk::SpAIBinder& in_bridge_handle,
      const std::vector<int64_t>& in_texture_ids,
      aidl::android::hardware::NativeWindow* out_surface) override;

  ndk::ScopedAStatus setExternalTextureSurfaceSize(
      const ::ndk::SpAIBinder& in_bridge_handle, int64_t in_texture_id,
      int32_t in_width, int32_t in_height) override;
  // End AIDL implementation.

  ndk::ScopedAStatus sendRequest(
      const ::ndk::SpAIBinder& in_bridge_handle,
      const std::vector<uint8_t>& in_data,
      const std::shared_ptr<
          ::aidl::imp::split_engine::ISplitEngineResponseHandler>& in_handler)
      override;

 private:
  // Provides a reference counted handle to a split engine bridge. When all
  // references are released, the bridge is destroyed via a call to
  // cleanupBridge.
  class BridgeHandle final
      : public aidl::imp::split_engine::BnSplitEngineToken {
   public:
    // The actual BridgeHandle does not need to be exposed outside the handle,
    // just the binder used for reference counting.
    static ::ndk::SpAIBinder CreateBridgeBinder(
        SplitEngineSharedMemoryBridgeService& bridgeService);

    virtual ~BridgeHandle();

   private:
    BridgeHandle(SplitEngineSharedMemoryBridgeService& bridgeService);
    BridgeHandle(const BridgeHandle&) = delete;
    BridgeHandle(BridgeHandle&&) = delete;
    BridgeHandle& operator=(const BridgeHandle&) = delete;
    BridgeHandle& operator=(BridgeHandle&&) = delete;

    void SetBridgeId(BridgeId bridge_id) { bridge_id_ = bridge_id; }

    friend class ndk::SharedRefBase;

   private:
    BridgeId bridge_id_;
    SplitEngineSharedMemoryBridgeService& bridgeService_;
  };

  // Provides a reference counted handle to a split engine bridge buffer. When
  // all references are released, the buffer is destroyed via a call to
  // cleanupBuffer.
  class BufferHandle final
      : public aidl::imp::split_engine::BnSplitEngineToken {
   public:
    // The actual BridgeHandle does not need to be exposed outside the handle,
    // just the binder used for reference counting.
    static ::ndk::SpAIBinder CreateBufferBinder(
        SplitEngineSharedMemoryBridgeService& bridgeService);

    virtual ~BufferHandle();

   private:
    BufferHandle(SplitEngineSharedMemoryBridgeService& bridgeService);
    BufferHandle(const BufferHandle&) = delete;
    BufferHandle(BufferHandle&&) = delete;
    BufferHandle& operator=(const BufferHandle&) = delete;
    BufferHandle& operator=(BufferHandle&&) = delete;

    void SetBufferId(BufferId buffer_id) { buffer_id_ = buffer_id; }

    friend class ndk::SharedRefBase;

   private:
    BufferId buffer_id_;
    SplitEngineSharedMemoryBridgeService& bridgeService_;
  };

  class NdkMessageGroupStorage
      : public SplitEngineSharedMemoryBridgeServiceImpl::MessageGroupStorage {
   public:
    NdkMessageGroupStorage(const ::ndk::SpAIBinder& buffer_handle)
        : buffer_handle_(buffer_handle) {}

   private:
    const ::ndk::SpAIBinder buffer_handle_;
  };

 protected:
  void CleanupBridge(BridgeId bridge_id);
  void CleanupBuffer(BufferId buffer_id);

 private:
  BaseView* view_;
  Executor* foreground_executor_;
  SplitEngineSharedMemoryBridgeServiceImpl impl_;
};

}  // namespace imp::split_engine

#endif  // THIRD_PARTY_IMPRESS_CORE_SPLIT_ENGINE_ANDROID_SPLIT_ENGINE_SHARED_MEMORY_BRIDGE_SERVICE_H_
