// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package imp.ar;

// option cc_api_version = 2;
option java_package = "com.google.ar.imp.proto";

// Enum that defines available face blend shapes.
enum FaceBlendShape {
  FACEBLENDSHAPE_UNKNOWN = 0;
  FACEBLENDSHAPE_BROW_DOWN_LEFT = 1;
  FACEBLENDSHAPE_BROW_DOWN_RIGHT = 2;
  FACEBLENDSHAPE_BROW_INNER_UP = 3;
  FACEBLENDSHAPE_BROW_OUTER_UP_LEFT = 4;
  FACEBLENDSHAPE_BROW_OUTER_UP_RIGHT = 5;
  FACEBLENDSHAPE_CHEEK_PUFF = 6;
  FACEBLENDSHAPE_CHEEK_SQUINT_LEFT = 7;
  FACEBLENDSHAPE_CHEEK_SQUINT_RIGHT = 8;
  FACEBLENDSHAPE_EYE_BLINK_LEFT = 9;
  FACEBLENDSHAPE_EYE_BLINK_RIGHT = 10;
  FACEBLENDSHAPE_EYE_LOOK_DOWN_LEFT = 11;
  FACEBLENDSHAPE_EYE_LOOK_DOWN_RIGHT = 12;
  FACEBLENDSHAPE_EYE_LOOK_IN_LEFT = 13;
  FACEBLENDSHAPE_EYE_LOOK_IN_RIGHT = 14;
  FACEBLENDSHAPE_EYE_LOOK_OUT_LEFT = 15;
  FACEBLENDSHAPE_EYE_LOOK_OUT_RIGHT = 16;
  FACEBLENDSHAPE_EYE_LOOK_UP_LEFT = 17;
  FACEBLENDSHAPE_EYE_LOOK_UP_RIGHT = 18;
  FACEBLENDSHAPE_EYE_SQUINT_LEFT = 19;
  FACEBLENDSHAPE_EYE_SQUINT_RIGHT = 20;
  FACEBLENDSHAPE_EYE_WIDE_LEFT = 21;
  FACEBLENDSHAPE_EYE_WIDE_RIGHT = 22;
  FACEBLENDSHAPE_JAW_FORWARD = 23;
  FACEBLENDSHAPE_JAW_LEFT = 24;
  FACEBLENDSHAPE_JAW_OPEN = 25;
  FACEBLENDSHAPE_JAW_RIGHT = 26;
  FACEBLENDSHAPE_MOUTH_CLOSE = 27;
  FACEBLENDSHAPE_MOUTH_DIMPLE_LEFT = 28;
  FACEBLENDSHAPE_MOUTH_DIMPLE_RIGHT = 29;
  FACEBLENDSHAPE_MOUTH_FROWN_LEFT = 30;
  FACEBLENDSHAPE_MOUTH_FROWN_RIGHT = 31;
  FACEBLENDSHAPE_MOUTH_FUNNEL = 32;
  FACEBLENDSHAPE_MOUTH_LEFT = 33;
  FACEBLENDSHAPE_MOUTH_LOWER_DOWN_LEFT = 34;
  FACEBLENDSHAPE_MOUTH_LOWER_DOWN_RIGHT = 35;
  FACEBLENDSHAPE_MOUTH_PRESS_LEFT = 36;
  FACEBLENDSHAPE_MOUTH_PRESS_RIGHT = 37;
  FACEBLENDSHAPE_MOUTH_PUCKER = 38;
  FACEBLENDSHAPE_MOUTH_RIGHT = 39;
  FACEBLENDSHAPE_MOUTH_ROLL_LOWER = 40;
  FACEBLENDSHAPE_MOUTH_ROLL_UPPER = 41;
  FACEBLENDSHAPE_MOUTH_SHRUG_LOWER = 42;
  FACEBLENDSHAPE_MOUTH_SHRUG_UPPER = 43;
  FACEBLENDSHAPE_MOUTH_SMILE_LEFT = 44;
  FACEBLENDSHAPE_MOUTH_SMILE_RIGHT = 45;
  FACEBLENDSHAPE_MOUTH_STRETCH_LEFT = 46;
  FACEBLENDSHAPE_MOUTH_STRETCH_RIGHT = 47;
  FACEBLENDSHAPE_MOUTH_UPPER_UP_LEFT = 48;
  FACEBLENDSHAPE_MOUTH_UPPER_UP_RIGHT = 49;
  FACEBLENDSHAPE_NOSE_SNEER_LEFT = 50;
  FACEBLENDSHAPE_NOSE_SNEER_RIGHT = 51;
  FACEBLENDSHAPE_TONGUE_OUT = 52;
  FACEBLENDSHAPE_COUNT = 53;
}
