// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

edition = "2024";

package imp;

import public "core/proto/imp.proto";

// Represents an impress material that can be referenced within a .isf file.
//
// Example usage:
//
// message FooState {
//   MaterialHandle material = 1;
// }
//
// WARNING: This is work in progress and not ready to be used yet.
message MaterialHandle {
  option (imp.native_type) = "::imp::MaterialHandle";
  option (imp.native_include) =
      "core/scene_handles/material_handle.h";
  option (imp.no_codegen) = true;

  // The name (or url) of the material.
  string url = 1;
}
