// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

edition = "2024";

package imp.editor;

import "core/math/math.proto";
import "core/scene_handles/scene_handles.proto";

message TransformWidgetAspectTranslateState {
  Float3 axis = 1;
}

message TransformWidgetAspectRotateState {
  Float3 axis = 1;
  // Implicit to prevent unset/true/false confusion from optional bool.
  bool camera_facing = 2;
}

message TransformWidgetAspectScaleState {
  Float3 axis = 1;
}
