// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

edition = "2023";

package test;

import "core/proto/imp.proto";
import "core/proto/imp_editions.proto";

option java_multiple_files = true;
option java_outer_classname = "TestEdition2023";
option (imp.impress_append_namespace) = true;

message TestEdition2023Message {
  message TestNestedMessage {
    int32 int_field = 1;
  }

  string string_field = 1;

  string string_field_optional_with_default = 2 [
    features.(.imp.impress_feature_set).presence_mode = OPTIONAL_WITH_DEFAULT,
    default = "hello"
  ];

  TestNestedMessage nested_message = 3;

  TestNestedMessage nested_message_optional_with_default = 4
      [features.(.imp.impress_feature_set).presence_mode =
           OPTIONAL_WITH_DEFAULT];
}
