/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef THIRD_PARTY_IMPRESS_CORE_NCSB_BASE_COMPONENT_POOL_H_
#define THIRD_PARTY_IMPRESS_CORE_NCSB_BASE_COMPONENT_POOL_H_

#include <cstddef>
#include <cstdint>
#include <memory>
#include <vector>

#include "absl/container/flat_hash_map.h"
#include "absl/status/status.h"
#include "absl/types/optional.h"
#include "filament/libs/utils/include/utils/Entity.h"
#include "core/async/future.h"
#include "core/async/future_common.h"
#include "core/common/entity_absl_hasher.h"
#include "core/common/holdable.h"
#include "core/common/invocable.h"
#include "core/common/rememberer.h"
#include "core/config.h"
#include "core/view/base_view.h"

#if IMP_RUNTIME(DEV)
#include "absl/strings/string_view.h"
#include "core/common/hash.h"
#include "core/editor/editor_info.h"
#include "core/ncsb/component_traits.h"
#endif  // IMP_RUNTIME(DEV)

namespace imp {

class Component;
class System;

class BaseComponentPool {
 public:
  using ComponentIndex = size_t;

  explicit BaseComponentPool(BaseView& view);

  virtual ~BaseComponentPool();

  bool Has(utils::Entity entity) const noexcept;
  ComponentIndex Get(utils::Entity entity) const noexcept;
  Component* Add(utils::Entity entity) noexcept;

  void Remove(utils::Entity entity) noexcept;
  void RemoveAll() noexcept;

  Component& GetRawComponent(ComponentIndex instance) noexcept;
  Component* TryGetRawComponentFromEntity(utils::Entity entity) noexcept;
  utils::Entity GetEntity(ComponentIndex instance) const noexcept;
  size_t GetComponentCount() const noexcept;

  virtual System* GetComponentSystem() { return nullptr; }

  virtual void NotifyActive(Component* component, bool active) noexcept = 0;

  // TODO: Refactor internal methods so they are no longer public,
  // and only accessible to the pool and ComponentManager.

  // Returns true is a component for this entity is currently loading async.
  //
  // NOTE: Internal implementation detail.
  // Please do not call outside ComponentManager or ComponentPool.
  bool Pending(utils::Entity entity) const noexcept;

  // If a component is loading async for this entity, cancels the async work.
  //
  // NOTE: Internal implementation detail.
  // Please do not call outside ComponentManager or ComponentPool.
  void CancelPending(utils::Entity entity) noexcept;

  // NOTE: Internal implementation detail.
  // Please do not call outside ComponentManager or ComponentPool.
  void PostSetup(utils::Entity entity, bool should_enable_component) noexcept;

  // Called by ComponentManager after calling an async Setup method.
  // This method generates a new future that will remove the component when
  // cancelled and returns it. It also stores a weak reference to the created
  // future for retrieval later, which is used for CancelPending and
  // GetSetupFuture (which is used for GetOrAddComponent).
  //
  // NOTE: Internal implementation detail.
  // Please do not call outside ComponentManager or ComponentPool.
  Future<absl::Status> MakeSetupFuture(utils::Entity entity,
                                       Future<absl::Status> future,
                                       bool should_enable_component);

  // Retrieve the future generated by MakeSetupFuture for a given entity.
  // This will return nullopt if the component already finished loading, if
  // the loading failed, or if the loading was cancelled.
  //
  // NOTE: Internal implementation detail.
  // Please do not call outside ComponentManager or ComponentPool.
  absl::optional<Future<absl::Status>> GetSetupFuture(utils::Entity entity);

  // Associates the lifetime of the holdable with the lifetime of the component
  // for e. Used by Component to implement the Remember protocol. See
  // third_party/impress/core/common/rememberer.h for details.
  Invocable<void()> Remember(utils::Entity e, Holdable holdable);

#if IMP_RUNTIME(DEV)
  // Returns true if this component is excluded from the editor.
  //
  // This is equivalent to ComponentT::kExcludeFromEditor, but accessible in a
  // type-erased manner.
  virtual bool IsExcludedFromEditor() const = 0;

  // Returns the type name of the component.
  //
  // This is equivalent to type_traits::kTypeName<ComponentT>, but accessible in
  // a type-erased manner.
  virtual absl::string_view GetTypeName() const = 0;

  // Returns the type url hash of the component's state type if it has IsfInfo.
  // Otherwise, returns std::nullopt.
  //
  // This is equivalent to ComponentT::IsfInfo::kTypeUrlHash, but accessible in
  // a type-erased manner.
  virtual std::optional<HashValue> GetStateTypeUrlHash() const = 0;

  // Invokes the component's DrawEditorUi method.
  virtual void DrawEditorUi(utils::Entity entity) = 0;
#endif  // IMP_RUNTIME(DEV)

 protected:
  // Data structure used to actually store component memory.
  //
  // Guarantees pointer stability of components.
  class ComponentStore {
   public:
    explicit ComponentStore(BaseComponentPool* pool);

    bool Has(utils::Entity entity) const;

    ComponentIndex GetIndex(utils::Entity entity) const;

    // Returns true if there are no components in the store.
    bool Empty() const;

    // Returns the number of components in the store.
    size_t GetComponentCount() const;

    // Returns the entity of the last component in the store.
    utils::Entity BackEntity() const;

    // Adds a new component of type T to the vector.
    // InstanceId can change when SwapAndPop is called.
    // Pointer is guaranteed to be stable.
    template <typename T>
    T* Emplace(utils::Entity entity);

    // Removes the component with the given entity from the store.
    void Remove(utils::Entity entity);

    // Access the raw component at the given index.
    //
    // Note 1: When components are removed, it may change the index of the
    // remaining components.
    //
    // Note 2: While iterating over components, if a component is removed there
    // may be a gap in the indices. The indices are compacted again after
    // iteration ends.
    Component& AtRaw(ComponentIndex index);
    const Component& AtRaw(ComponentIndex index) const;

    Component* TryGetRaw(utils::Entity entity);

    template <typename T>
    T& At(ComponentIndex index);

    template <typename T, typename Fn>
    void ForEach(Fn fn);

    template <typename T, typename Fn>
    void UpdateEach(Fn fn);

   private:
    void TryDensifyComponentsVector();

    // Unique Pointer with custom deleter to store components in a type-erased
    // pointer stable way. The custom deleter is used so that components are not
    // required to have virtual destructors.
    using ComponentPtr = std::unique_ptr<Component, void (*)(Component*)>;

    // Uses a vector under the hood to actually store the component pointers.
    // When adding a component, we only ever add to the end.
    // When removing a component pointer, we swap it to the end (if it isn't at
    // the end already) and remove it from the end.
    std::vector<ComponentPtr> components_;

    absl::flat_hash_map<utils::Entity, ComponentIndex, EntityHasher>
        entities_to_indices_;

    // Used to track when we are in the middle of iterating over components.
    //
    // This is used to handle the case where a component is removed during
    // iteration. Normally, we swap and pop the removed component to keep the
    // vector compact but that can cause the iteration to skip over components.
    //
    // If iterating, we don't compact the vector until after iteration ends.
    //
    // This is an integer instead of a bool because we can have nested
    // iterations.
    uint32_t iterating_depth_ = 0;

    // The number of indices in the components vector that are empty.
    //
    // This is only used when components are removed during iteration, which
    // leads to the vector temporarily having gaps in it.
    //
    // This is used to determine if the vector needs to be compacted, and to
    // ensure that GetComponentCount and Empty work correctly while iterating.
    uint32_t free_indices_count_ = 0;

    BaseComponentPool* pool_;
  };

  ComponentStore& GetComponents() { return components_; }

  BaseView& GetView() { return view_; }

  void Forget(utils::Entity e);

  // Adds a new component and returns a pointer to it.
  virtual Component* Emplace(utils::Entity entity) noexcept = 0;

  // Calls Cleanup on the component with the instance id passed in.
  virtual void Cleanup(Component& component) noexcept = 0;

  // Called if there are no entries in the pool.
  virtual void BeforeFirstAdded() noexcept {}

  // Called after a component has been added and then setup.
  virtual void AfterAdd(Component& component) noexcept {}

  // Called when a component is being removed, before cleanup begins.
  // Called right before 'AfterLastRemoved.'
  virtual void BeforeRemove(Component& component) noexcept {}

  // Called after cleanup if there are now no more entries in the pool.
  virtual void AfterLastRemoved() noexcept {}

 private:
  BaseView& view_;
  ComponentStore components_;
  absl::flat_hash_map<utils::Entity, Rememberer, EntityHasher> rememberers_;
  absl::flat_hash_map<utils::Entity, WeakFuture<absl::Status>, EntityHasher>
      weak_setup_futures_;
};

template <typename T>
T* BaseComponentPool::ComponentStore::Emplace(utils::Entity entity) {
  components_.push_back(ComponentPtr(
      new T(), +[](Component* raw_component) {
        T* component = static_cast<T*>(raw_component);
        delete component;
      }));

  entities_to_indices_[entity] = components_.size() - 1;

  return static_cast<T*>(components_.back().get());
}

template <typename T>
T& BaseComponentPool::ComponentStore::At(
    BaseComponentPool::ComponentIndex index) {
  return static_cast<T&>(AtRaw(index));
}

template <typename T, typename Fn>
void BaseComponentPool::ComponentStore::ForEach(Fn fn) {
  ++iterating_depth_;

  // Iterate using indices so that it is safe to add/remove components during
  // iteration.
  for (ComponentIndex i = 0; i < components_.size(); i++) {
    T* component = static_cast<T*>(components_[i].get());

    // If the component is null, it is implied that it was removed during
    // iteration. After iteration ends, the vector will be compacted.
    if (!component) {
      continue;
    }

    if (!pool_->Pending(component->GetEntity())) {
      fn(component);
    }
  }

  --iterating_depth_;

  TryDensifyComponentsVector();
}

template <typename T, typename Fn>
void BaseComponentPool::ComponentStore::UpdateEach(Fn fn) {
  ++iterating_depth_;

  // Iterate using indices so that it is safe to add/remove components during
  // iteration.
  for (ComponentIndex i = 0; i < components_.size(); i++) {
    T* component = static_cast<T*>(components_[i].get());

    // If the component is null, it is implied that it was removed during
    // iteration. After iteration ends, the vector will be compacted.
    if (!component) {
      continue;
    }

    if (!pool_->Pending(component->GetEntity())) {
#if IMP_RUNTIME(DEV)
      // Skip components that should not be updated in editor draft/pause mode.
      if constexpr (!component_traits::kShouldRunInEditMode<T>) {
        if (editor::ShouldNotUpdate(pool_->GetView().GetRegistry()) &&
            !component->IsEditorStaging()) {
          continue;
        }
      }
#endif  // IMP_RUNTIME(DEV)
      if constexpr (T::kUpdateMode == T::UpdateMode::kAlwaysUpdate) {
        fn(component);
      } else {
        if (component->IsActive()) {
          fn(component);
        }
      }
    }
  }

  --iterating_depth_;

  TryDensifyComponentsVector();
}

}  // namespace imp

#endif  // THIRD_PARTY_IMPRESS_CORE_NCSB_BASE_COMPONENT_POOL_H_
