// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Defines the proto for render settings
// For now, it's only intended to be used by SwapChainRenderer

edition = "2024";

package imp;

import "core/view/utils/proto/cache_config.proto";
import "core/view/utils/proto/filament_feature_flag.proto";
import "core/view/utils/proto/render_settings.proto";

// option cc_api_version = 2;
option java_package = "com.google.ar.imp.core";

// Defines temporary flags used for testing code in development.
message ExperimentalFeatureFlags {
  // OWNERS: eugenecys
  // BUG: b/452459028
  // PLATFORMS: ANDROID
  // ACTION: Clean up by 2026-01-17
  bool glyph_atlas_use_hardware_rendering = 1 [default = true];

  // OWNERS: eugenecys
  // BUG: b/385221395
  // PLATFORMS: ANDROID
  // ACTION: Clean up by 2026-01-17
  bool glyph_atlas_force_reset_on_view_resumed = 2 [default = true];

  // OWNERS: eugenecys, exv
  // BUG: b/454131370
  // PLATFORMS: ANDROID
  // ACTION: Clean up by 2026-01-24
  bool glyph_atlas_force_auto_method_rendering = 3 [default = false];

  // OWNERS: artyompp
  // BUG: b/469883152
  // PLATFORMS: ANDROID
  // ACTION: Clean up by 2026-02-26
  bool surface_texture_memory_leak_fix = 4 [default = false];

  // OWNERS: faaland
  // BUG: b/361658541
  // PLATFORMS: IOS
  // ACTION: Clean up by 2026-06-01
  bool enable_set_presentation_time = 5 [default = false];

  // OWNERS: jagannathnalla
  // BUG: b/476917931
  // PLATFORMS: ANDROID
  // ACTION: Clean up by 2026-03-31
  bool force_individual_glyph_source_instances = 6 [default = false];
}

message ViewConfig {
  enum ShaderCachingMode {
    SHADER_CACHING_MODE_UNSPECIFIED = 0;
    SHADER_CACHING_MODE_ENABLED = 1;
    SHADER_CACHING_MODE_DISABLED = 2;
  }

  enum DefaultLightingLoading {
    DEFAULT_LIGHTING_LOADING_UNSPECIFIED = 0;
    DEFAULT_LIGHTING_LOADING_ENABLED = 1;
    DEFAULT_LIGHTING_LOADING_DISABLED = 2;
  }

  render_settings.ViewRenderSettings main_view_render_settings = 1;
  ShaderCachingMode shader_caching_mode = 2
      [default = SHADER_CACHING_MODE_DISABLED];
  DefaultLightingLoading default_lighting_loading = 3
      [default = DEFAULT_LIGHTING_LOADING_ENABLED];

  // The amount of time the foreground executor will pump per frame. The default
  // is 4ms.
  float foreground_executor_timeout_ms = 4 [default = 4.0];

  // The amount of time the background executor will pump per frame if Impress
  // is using a background executor that requires explicit pumping. The default
  // is 1ms.
  float background_executor_timeout_ms = 5 [default = 1.0];

  // If true, use the system's own frame scheduled handler instead of providing
  // a callback handler to Filament.
  bool use_system_frame_scheduled_handler = 6 [default = false];

  // The size of the texture used by the GlyphAtlas.
  enum GlyphAtlasTextureSize {
    // A 2048x2048 texture size.
    SIZE2048 = 0;
    // A 2048x4096 texture size.
    SIZE2048X4096 = 1;
    // A 4096x4096 texture size.
    SIZE4096 = 2;
    // A 8x8 grid of 256x256 textures (2048x2048 total).
    SIZE256X256X8X8 = 3;
  }

  // The size of the texture used by the GlyphAtlas. The default is SIZE2048,
  // which is 2048x2048.
  GlyphAtlasTextureSize glyph_atlas_texture_size = 7 [default = SIZE2048];

  CacheConfig cache_config = 9;

  // If true, imp::Future will attempt to synchronously complete all pending
  // work upon cancellation and/or destruction.
  // What this means practically is that futures scheduled on the foreground
  // (imp::SimpleExecutor) executor will be guaranteed to have a result when
  // either the future is cancelled or its last reference is released. It also
  // means that any held imp::Holdable or captured objects will be released
  // after either cancellation or destruction.
  // This behavior only applies to Executors that have implemented
  // imp::Executor::InvokeScheduledTask().
  // The flag is enabled by default.
  bool enable_synchronous_future_cancellation = 10 [default = true];

  // Defines calls equivalent to filament::Engine::setFeatureFlag, executed when
  // the Impress View is constructed.
  repeated FilamentFeatureFlag filament_feature_flags = 11;

  // Defines temporary flags for impress code in development.
  ExperimentalFeatureFlags experimental_feature_flags = 12;

  // If true, the swap chain will be created with an alpha channel.
  bool use_transparent_swap_chain = 13 [default = false];
}
