/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef THIRD_PARTY_IMPRESS_CORE_RESOURCES_RESOURCEDEFINITION_H_
#define THIRD_PARTY_IMPRESS_CORE_RESOURCES_RESOURCEDEFINITION_H_

#include "absl/strings/string_view.h"

namespace imp {
namespace resources {

// Defines an Impress resource/asset that can be loaded via the Impress
// AssetManager.
//
// This may refer to an embedded file, or to a remote url. Typically, this will
// be determined by a build configuration (i.e. embedded file in development
// builds, remote url in production builds).
//
// Resource definitions are typically created by generated headers using the
// imp_assets rule.
//
// See:
// third_party/impress/build_tools/assets.bzl
//
//
// *Note*
//
// Resources must be registered before they can be loaded.
//
// Resources are automatically registered when passed into the AssetManager.
//
// However, resources must be registered explicitly to load them by their string
// identifier. For example, when referencing a resource by string in a .isf
// file.
//
// To explicitly register resources, call the function
// foo_resources::RegisterPathToFoo() generated by the imp_assets rule.
//
// Registering the resources makes it possible to reference a resource by
// nothing but its string identifier and have it automatically switch between
// loading an embedded version of a resource and a remote version of a resource
// based on if the imp_assets were embedded in a build.
//
// See:
// third_party/impress/core/resources/resource_embedded_h.tmpl
class ResourceDefinition {
 public:
  using RegisterResourceFn = void();

  template <size_t N>
  using StringLiteral = const char[N];

  // Constructs a ResourceDefinition from just an identifier along with a
  // pointer to a function for registering the packages resources.
  //
  // Used by imp_assets rule for resources that are embedded.
  template <size_t IdentifierN>
  constexpr ResourceDefinition(StringLiteral<IdentifierN> const& identifier,
                               RegisterResourceFn* register_resource_fn)
      : identifier_(identifier, IdentifierN - 1),
        url_(identifier_),
        register_resource_fn_(register_resource_fn) {}

  // Constructs a ResourceDefinition from both an identifier and a url along
  // with a pointer to a function for registering the packages resources.
  //
  // Used by imp_assets rule for resources that are remote.
  template <size_t IdentifierN, size_t UrlN>
  constexpr ResourceDefinition(StringLiteral<IdentifierN> const& identifier,
                               StringLiteral<UrlN> const& url,
                               RegisterResourceFn* register_resource_fn)
      : identifier_(identifier, IdentifierN - 1),
        url_(url, UrlN - 1),
        register_resource_fn_(register_resource_fn) {}

  absl::string_view GetIdentifier() const;

  // Retrieve the url for addressing this resource, used to load the resource
  // via the Impress AssetManager.
  //
  // The url may be a remote address, or an identifier for an embedded file.
  //
  // If this resource definition refers to an embedded file, then the embedded
  // files from this definition's imp_assets rule will be lazily registered the
  // first time GetUrl() is called.
  absl::string_view GetUrl() const;

 private:
  // Both of the below fields are safe to store as string_view because a
  // ResourceDefinition can only be constructed from a string literal, therefore
  // the lifetime of the data is guaranteed to persist.

  // Identifier for referencing the resource.
  // This is always the path to the resource on google3.
  //
  // This identifier can be used to reference a resource in a .isf file, and it
  // will automatically switch between remote/embedded assets.
  absl::string_view identifier_;

  // The Url for the resource.
  //
  // For embedded resources, this is always the same as the identifier.
  // For remote resources, this is the real network location of the file.
  absl::string_view url_;

  RegisterResourceFn* register_resource_fn_;
};

}  // namespace resources
}  // namespace imp

#endif  // THIRD_PARTY_IMPRESS_CORE_RESOURCES_RESOURCEDEFINITION_H_
