// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

include "core/common/schemas/math.fbs";

namespace imp.schemas;

enum InteractivityVariableType : uint8 {
  BOOL,
  INT,
  FLOAT,
  FLOAT2,
  FLOAT3,
  FLOAT4,
  MAT2F,
  MAT3F,
  MAT4F
}

union InteractivityValue {
  Bool,
  Int,
  Float,
  Float2,
  Float3,
  Float4,
  Mat2f,
  Mat3f,
  Mat4f,
  String,
}

table InteractivityVariable {
  id : string (required);
  value: InteractivityValue (required);
}

table InteractivityNodeFlow {
  id : string (required);
  node : uint32;
  socket : string (required);
}

union InteractivityConfigurationValue {
  Int,
  String,
  Bool,
  Float,
  IntArray,
}

enum InteractivityNodeConfigurationType : uint8 {
  VARIABLE,
  NUMBER_OF_OUTPUT_FLOWS,
  POINTER,
  EVENT,
  NODE_INDEX,
  STOP_PROPAGATION,
  EASING_TYPE,
  EASING_DURATION,
  CASES,
  TYPE,
  NUMBER_OF_INPUT_FLOWS,
  IS_RANDOM,
  IS_LOOP,
  MESSAGE,
  INITIAL_INDEX,
  VARIABLES,
  USE_SLERP,
  SEVERITY,
}

table InteractivityNodeConfiguration {
  id : InteractivityNodeConfigurationType;
  value : InteractivityConfigurationValue (required);
}

// The union is stored in a table instead of being used directly as the API
// exposed by this is a lot more usable.
union InteractivityNodeValueType {
  InteractivityVariable,
  InteractivityNodeFlow,
}

table InteractivityNodeValue {
  value: InteractivityNodeValueType;
}

// TODO: Add support for declaring custom nodes.
table Declaration {
  op : string (required);
}

table InteractivityNode {
  declaration : uint32;
  // TODO: Investigate if we can remove this index field.
  index : uint32;
  flows : [InteractivityNodeFlow];
  configuration : [InteractivityNodeConfiguration];
  values: [InteractivityNodeValue];
}

table InteractivityEvent {
  id : string (required);
  values: [InteractivityVariable];
}

table InteractivityGraphTypeData {
  type : InteractivityVariableType;
}

table InteractivityGraph {
  declarations : [Declaration];
  nodes : [InteractivityNode];
  variables : [InteractivityVariable];
  events : [InteractivityEvent];
  types: [InteractivityGraphTypeData];
}

table Interactivity {
  graphs : [InteractivityGraph];
  graph : uint32;
}

root_type Interactivity;
