// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package imp;

import "core/math/math.proto";
import "core/physics/collidable_type.proto";
import "core/proto/imp.proto";

// Message for holding 3 boolean values, typically for axes.
message Bool3 {
  bool x = 1;
  bool y = 2;
  bool z = 3;
}

// Serialized data for RigidBody.
message RigidBodyState {
  // Decides how the rigid body will react to collision, physics law and direct
  // changes of properties.
  enum MotionMode {
    // The rigid body's position is controlled by directly setting the transform
    // of the node, ignoring gravity, impulses, and forces. The rigid body can
    // be collided with, but will not react to collisions.
    DIRECTED_DEFAULT = 0;
    // The rigid body's position cannot be set by the user. It reacts to gravity
    // and other impulse and force. It is collidable and will react to the
    // collsion.
    SIMULATED = 1;
    // The rigid body's position cannot be changed once it is set.
    NONMOVABLE = 2;
  }

  MotionMode motion_mode = 1;
  float mass = 2;
  optional float friction = 3;
  physics.CollidableType collidable_type = 4;
  Float3 gravity = 5 [(imp.optional_type) = ABSL_OPTIONAL];
  float restitution = 6;
  Float3 linear_velocity = 7 [(imp.editor_control) = { read_only: {} }];
  Float3 angular_velocity = 8 [(imp.editor_control) = { read_only: {} }];

  // Flags to freeze position along x, y, or z axes.
  Bool3 lock_position = 9 [(imp.optional_type) = ABSL_OPTIONAL];
  // Flags to freeze rotation around x, y, or z axes.
  Bool3 lock_rotation = 10 [(imp.optional_type) = ABSL_OPTIONAL];

  // Simulates drag / air resistance on the angular velocity of the rigid
  // body, essentially slowing down the velocity over time even without
  // friction or collisions. 0 means no damping, 1 means maximum damping.
  float angular_damping = 11;

  // Simulates drag / air resistance on the linear velocity of the rigid
  // body, essentially slowing down the velocity over time even without
  // friction or collisions. 0 means no damping, 1 means maximum damping.
  float linear_damping = 12;
}
