/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef THIRD_PARTY_IMPRESS_CORE_COMMON_FLATBUFFER_HELPERS_H_
#define THIRD_PARTY_IMPRESS_CORE_COMMON_FLATBUFFER_HELPERS_H_

#include <cassert>
#include <cstddef>
#include <cstdint>
#include <type_traits>
#include <utility>
#include <vector>

#include "flatbuffers/flatbuffer_builder.h"
#include "flatbuffers/flatbuffers.h"
#include "flatbuffers/idl.h"
#include "flatbuffers/table.h"
#include "flatbuffers/vector.h"
#include "core/common/buffer_access.h"
#include "core/common/optional_error.h"
#include "core/common/paired_span.h"
#include "core/common/paired_vector.h"
#include "core/common/schemas/math_generated.h"
#include "core/math/flatbuffer_support.h"
#include "core/math/mat.h"
#include "core/math/vec.h"
#include "mediapipe/framework/port/status_macros.h"

namespace imp {

// Specialized ReadFromFlatbuffer for subtypes of flatbuffer::Table
// (i.e. the raw flatbuffer types)
template <class T,
          std::enable_if_t<std::is_base_of<flatbuffers::Table, T>{}, int> = 0>
OptionalError ReadFromFlatbuffer(const uint8_t* flatbuffer, const T** dest) {
  *dest = nullptr;
  if (!flatbuffer) {
    return Error("Internal Error: missing required 'flatbuffer' parameter");
  }
  const T* root = flatbuffers::GetRoot<T>(flatbuffer);
  if (root == nullptr) {
    return Error("Internal Error: flatbuffer root type mismatch");
  }
  *dest = root;

  return NoError();
}

template <class T,
          std::enable_if_t<std::is_base_of<flatbuffers::Table, T>{}, int> = 0>
OptionalError GetRoot(const BufferAccess& flatbuffer, const T** dest) {
  *dest = nullptr;
  if (flatbuffer.Empty()) {
    return Error("Provided buffer is empty");
  }
  const T* root = flatbuffers::GetRoot<T>(flatbuffer.Data());
  if (root == nullptr) {
    return Error("Flatbuffer root type mismatch");
  }
  *dest = root;

  return NoError();
}

// Specialized ReadFromFlatbuffer for subtypes of flatbuffer::NativeTable
// (i.e. the flatbuffer object-api types)
template <class T, std::enable_if_t<
                       std::is_base_of<flatbuffers::NativeTable, T>{}, int> = 0>
OptionalError ReadFromFlatbuffer(const uint8_t* flatbuffer, T* dest) {
  const typename T::TableType* table;
  MP_RETURN_IF_ERROR(ReadFromFlatbuffer(flatbuffer, &table));
  table->UnPackTo(dest);
  return NoError();
}

// Serialize `source` (a *DefT generated by flatbuffers) to a binary stream.
template <class T, std::enable_if_t<
                       std::is_base_of<flatbuffers::NativeTable, T>{}, int> = 0>
OptionalError WriteToFlatbuffer(T* source, BufferAccess* access) {
  if (!source) {
    return Error("Internal Error: missing required 'source' parameter");
  }
  if (!access) {
    return Error("Internal Error: missing required 'flatbuffer' parameter");
  }
  flatbuffers::FlatBufferBuilder fbb(1024);
  fbb.Finish(T::TableType::Pack(fbb, source));

  const uint8_t* data = fbb.GetBufferPointer();
  const size_t size = fbb.GetSize();

  if (!size) {
    return Error("Internal error: Failed to convert object to flatbuffer");
  }

  *access = BufferAccess::Clone(data, size);
  return NoError();
}

// Release the memory owned by a flatbuffer builder into a buffer access.
OptionalError ReleaseToBufferAccess(flatbuffers::FlatBufferBuilder* fbb,
                                    BufferAccess* access);

// Release the memory owned by a flatbuffer parser (which just uses a builder).
inline OptionalError ReleaseToBufferAccess(flatbuffers::Parser* parser,
                                           BufferAccess* access) {
  return ReleaseToBufferAccess(&parser->builder_, access);
}

inline BufferAccess WrappedAccess(const flatbuffers::Vector<uint8_t>* vec) {
  return BufferAccess::Wrap(vec->Data(), vec->size());
}

// Helper type to wrap a pointer to a flatbuffer struct along with a buffer
// access that contains that pointer within it's view.
template <typename T>
class FlatBufferAccess {
 public:
  // Default-construct to empty state.
  FlatBufferAccess() : root_(nullptr), buffer_() {}

  // Manual construction for when root != GetRoot(), e.g. nested flatbuffers.
  FlatBufferAccess(const T* root, BufferAccess buffer)
      : root_(root), buffer_(std::move(buffer)) {}

  // Helper method to steal a builder's constructed buffer and it's root.
  friend inline OptionalError CreateFlatBufferAccess(
      flatbuffers::FlatBufferBuilder* fbb, FlatBufferAccess<T>* out_access) {
    BufferAccess buffer;
    MP_RETURN_IF_ERROR(ReleaseToBufferAccess(fbb, &buffer));
    MP_RETURN_IF_ERROR(CreateFlatBufferAccess(std::move(buffer), out_access));
    return NoError();
  }
  // Helper method to get access to the root structure in a buffer.
  friend inline OptionalError CreateFlatBufferAccess(
      BufferAccess buffer, FlatBufferAccess<T>* out_access) {
    const T* root = nullptr;
    MP_RETURN_IF_ERROR(GetRoot(buffer, &root));
    *out_access = FlatBufferAccess{root, std::move(buffer)};
    return NoError();
  }
  static FlatBufferAccess<T> CloneNestedFlatBuffer(const T* root,
                                                   const uint8_t* data,
                                                   size_t size) {
    size_t offset = reinterpret_cast<const uint8_t*>(root) - data;
    assert(offset < size);
    BufferAccess buffer = BufferAccess::Clone(data, size);
    const T* cloned_root = reinterpret_cast<const T*>(buffer.Data() + offset);
    return FlatBufferAccess<T>(cloned_root, std::move(buffer));
  }
  // Accessors.
  const T* Root() const { return root_; }
  const BufferAccess& Buffer() const { return buffer_; }

  // Convenience operators.
  const T* operator->() const { return Root(); }
  const T* operator*() const { return Root(); }

  // Releases ownership of the contained buffer to the caller.
  BufferAccess&& ReleaseBuffer() { return std::move(buffer_); }

 private:
  const T* root_ = nullptr;
  BufferAccess buffer_;
};

inline float FromFlatbuffer(const schemas::Float& v) { return v.value(); }
inline float2 FromFlatbuffer(const schemas::Float2& v) {
  return {v.x(), v.y()};
}
inline float3 FromFlatbuffer(const schemas::Float3& v) {
  return {v.x(), v.y(), v.z()};
}
inline float4 FromFlatbuffer(const schemas::Float4& v) {
  return {v.x(), v.y(), v.z(), v.w()};
}
inline int FromFlatbuffer(const schemas::Int& v) { return v.value(); }
inline int2 FromFlatbuffer(const schemas::Int2& v) { return {v.x(), v.y()}; }
inline int3 FromFlatbuffer(const schemas::Int3& v) {
  return {v.x(), v.y(), v.z()};
}
inline int4 FromFlatbuffer(const schemas::Int4& v) {
  return {v.x(), v.y(), v.z(), v.w()};
}
inline bool FromFlatbuffer(const schemas::Bool& v) { return v.value(); }
inline bool2 FromFlatbuffer(const schemas::Bool2& v) { return {v.x(), v.y()}; }
inline bool3 FromFlatbuffer(const schemas::Bool3& v) {
  return {v.x(), v.y(), v.z()};
}
inline bool4 FromFlatbuffer(const schemas::Bool4& v) {
  return {v.x(), v.y(), v.z(), v.w()};
}
inline mat3f FromFlatbuffer(const schemas::Mat3f& v) {
  return mat3f{v.m00(), v.m01(), v.m02(),  //
               v.m10(), v.m11(), v.m12(),  //
               v.m20(), v.m21(), v.m22()};
}
std::vector<mat3f> FromFlatbuffer(schemas::Mat3fVector* v);

// Converts a paired vector of Typed IDs into a flatbuffer vector using the
// underlying type. Sfinae on T::ValueType ensures this is only considered
// when T is a TypedId.
template <typename D, typename T, typename R,
          std::enable_if_t<std::is_same<D, typename T::ValueType>{}, int> = 0>
flatbuffers::Offset<flatbuffers::Vector<D>> CreateVector(
    flatbuffers::FlatBufferBuilder& fbb, const PairedVector<T, R>& vector) {
  return fbb.CreateVector(reinterpret_cast<const D*>(vector.data()),
                          vector.size());
}

// Converts a paired span of Typed IDs into a flatbuffer vector using the
// underlying type. Sfinae on T::ValueType ensures this is only considered
// when T is a TypedId.
template <typename D, typename T, typename R,
          std::enable_if_t<std::is_same<D, typename T::ValueType>{}, int> = 0>
flatbuffers::Offset<flatbuffers::Vector<D>> CreateVector(
    flatbuffers::FlatBufferBuilder& fbb, const PairedSpan<T, R>& vector) {
  return fbb.CreateVector(reinterpret_cast<const D*>(vector.data()),
                          vector.size());
}

// Converts a paired vector into a flatbuffer vector using the same type.
template <
    typename D, typename T, typename R,
    std::enable_if_t<std::is_same<D, T>{} && flatbuffers::is_scalar<T>::value,
                     int> = 0>
flatbuffers::Offset<flatbuffers::Vector<D>> CreateVector(
    flatbuffers::FlatBufferBuilder& fbb, const PairedVector<T, R>& vector) {
  return fbb.CreateVector(vector.data(), vector.size());
}

// Converts a paired span into a flatbuffer vector using the same type.
template <
    typename D, typename T, typename R,
    std::enable_if_t<std::is_same<D, T>{} && flatbuffers::is_scalar<T>::value,
                     int> = 0>
flatbuffers::Offset<flatbuffers::Vector<D>> CreateVector(
    flatbuffers::FlatBufferBuilder& fbb, const PairedSpan<T, R>& span) {
  return fbb.CreateVector(span.data(), span.size());
}

// Converts a paired vector of offsets into a flatbuffer vector using the same
// type.
template <typename T, typename R>
flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<T>>> CreateVector(
    flatbuffers::FlatBufferBuilder& fbb,
    const PairedVector<flatbuffers::Offset<T>, R>& vector) {
  return fbb.CreateVector(vector.data(), vector.size());
}

// Converts a paired span of offsets into a flatbuffer vector using the same
// type.
template <typename T, typename R>
flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<T>>> CreateVector(
    flatbuffers::FlatBufferBuilder& fbb,
    const PairedSpan<flatbuffers::Offset<T>, R>& span) {
  return fbb.CreateVector(span.data(), span.size());
}

// Converts a paired vector of native structs into a flatbuffer vector using
// the type produced by flatbuffers::Pack().
template <typename D, typename T, typename R>
flatbuffers::Offset<flatbuffers::Vector<const D*>> CreateVectorOfNativeStructs(
    flatbuffers::FlatBufferBuilder& fbb, const PairedVector<T, R>& vector) {
  return fbb.CreateVectorOfNativeStructs<D>(vector.data(), vector.size());
}

// Converts a paired span of native structs into a flatbuffer vector using the
// type produced by flatbuffers::Pack().
template <typename D, typename T, typename R>
flatbuffers::Offset<flatbuffers::Vector<const D*>> CreateVectorOfNativeStructs(
    flatbuffers::FlatBufferBuilder& fbb, const PairedSpan<T, R>& span) {
  return fbb.CreateVectorOfNativeStructs<D>(span.data(), span.size());
}

// Converts a paired vector of strings into a flatbuffer vector of strings.
template <typename T, typename R>
flatbuffers::Offset<
    flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>>
CreateVectorOfStrings(flatbuffers::FlatBufferBuilder& fbb,
                      const PairedVector<T, R>& vector) {
  return fbb.CreateVectorOfStrings(vector.begin(), vector.end());
}

// Converts a paired span of strings into a flatbuffer vector of strings.
template <typename T, typename R>
flatbuffers::Offset<
    flatbuffers::Vector<flatbuffers::Offset<flatbuffers::String>>>
CreateVectorOfStrings(flatbuffers::FlatBufferBuilder& fbb,
                      const PairedSpan<T, R>& span) {
  return fbb.CreateVectorOfStrings(span.begin(), span.end());
}

}  // namespace imp

#endif  // THIRD_PARTY_IMPRESS_CORE_COMMON_FLATBUFFER_HELPERS_H_
