// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package imp;

import "core/math/math.proto";
import "core/proto/imp.proto";
import "core/scene_handles/scene_handles.proto";

message HingeConstraintState {
  // The node that holds a rigid body A that is subject to this constraint.
  NodeSceneHandle connected_node = 1;

  // The pivot of the constraint frame in the connected node(that holds rigid
  // body A)'s local space.
  Float3 connected_pivot = 2;

  // The axis of the constraint frame in the connected node(that holds rigid
  // body A)'s local space. It is the axis of the hinge.
  Float3 connected_axis = 3;

  // Only used when the constraint is between two rigid bodies. Indicates the
  // pivot/offset of the constraint frame from rigid body (B). Note that rigid
  // body (B) is attached the same node that owns the constraint.
  Float3 pivot = 4 [(imp.optional_type) = ABSL_OPTIONAL];

  // Only used when the constraint is between two rigid bodies. Indicates the
  // axis of the hinge in the local space of rigid body (B). Note that rigid
  // body (B) is attached the same node that owns the constraint.
  Float3 axis = 5 [(imp.optional_type) = ABSL_OPTIONAL];

  // if it will calculate the connected pivot based on the transforms of the
  // two rigid bodies.
  // If there is only one rigid body (the connected node), the pivot will be
  // interpreted as the world position of the constraint.
  bool auto_configure = 6;

  // The limits of the hinge expressed in degrees around the rotation axis.
  float lower_limit = 7;
  float upper_limit = 8;

  // How aggressively the joint resists movement as it nears the limits
  float bias_factor = 9;
  float relaxation_factor = 10;

  // Whether the motor is enabled and its parameters.
  bool angular_motor_enabled = 11;
  float angular_motor_velocity = 12;
  float angular_motor_max_impulse = 13;

  // If the constraint is ready (is it functioning, ie it is connected to
  // valid rigid bodies)
  bool is_ready = 14 [(imp.editor_control) = { read_only: {} }];
}
