// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package imp;

import "core/math/math.proto";
import "core/scene_handles/scene_handles.proto";

message Point2PointConstraintState {
  // The node that holds a rigid body A that is subject to this constraint.
  NodeSceneHandle connected_node = 1;

  // The pivot of the constraint frame in the connected node(that holds rigid
  // body A)'s local space.
  Float3 connected_pivot = 2;

  // Only used when the constraint is between two rigid bodies. Indicates the
  // pivot/offset of the constraint frame from rigid body (B). Note that rigid
  // body (B) is attached the same node that owns the constraint.
  Float3 pivot = 3 [(imp.optional_type) = ABSL_OPTIONAL];

  // if it will calculate the connected pivot based on the transforms of the
  // two rigid bodies.
  // If there is only one rigid body (the connected node), the pivot will be
  // interpreted as the world position of the constraint.
  bool auto_configure = 4;

  // If the constraint is valid (is it functioning, ie it is connected to valid
  // rigid bodies)
  bool is_valid = 5;
}
