// Copyright 2025 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package imp;

import "core/math/math.proto";
import "core/proto/imp.proto";
import "core/scene_handles/scene_handles.proto";

message SliderConstraintState {
  // The node that holds a rigid body A that is subject to this constraint.
  NodeSceneHandle connected_node = 1;

  // Indicates the pivot/offset of the constraint frame from rigid body (B).
  // Note that rigid body (B) is attached the same node that owns the
  // constraint.
  Float3 pivot = 2;

  // The rotation for the constraint frame from rigid body (B).
  Float3 axis = 3 [(imp.optional_type) = ABSL_OPTIONAL];
  Float3 up_axis = 4 [(imp.optional_type) = ABSL_OPTIONAL];

  // if it will calculate the connected pivot and axis based on the transforms
  // of the two rigid bodies. If there is only one rigid body (the connected
  // node), the pivot and axiswill be interpreted as the world transform of the
  // constraint.
  bool auto_configure = 5;

  // The pivot of the constraint frame in the connected node(that holds rigid
  // body A)'s local space. These are used only when auto_configure is false.
  Float3 connected_pivot = 6 [(imp.optional_type) = ABSL_OPTIONAL];

  // The axis of the constraint frame in the connected node(that holds rigid
  // body A)'s local space.
  Float3 connected_axis = 7 [(imp.optional_type) = ABSL_OPTIONAL];

  // The up axis of the constraint frame in the connected node(that holds rigid
  // body A)'s local space. Together withe the axis, it defines the constraint
  // rotation.
  Float3 connected_up_axis = 8 [(imp.optional_type) = ABSL_OPTIONAL];

  // The limits for the linear movement
  float linear_lower_limit = 9;
  float linear_upper_limit = 10;

  // The force and desired velocity for the linear motor
  float max_linear_motor_force = 11;
  float max_linear_motor_velocity = 12;

  // The parameters for hitting the linear limits
  float softness_linear_limit = 13;
  float restitution_linear_limit = 14;
  float damping_linear_limit = 15;

  // The parameters for moving against the constraint axis (on orthogonal axes)
  float softness_ortho_linear_limit = 16;
  float restitution_ortho_linear_limit = 17;
  float damping_ortho_linear_limit = 18;

  // If the constraint is ready (is it functioning, ie it is connected to valid
  // rigid bodies)
  bool is_ready = 19 [(imp.editor_control) = { read_only: {} }];
}
