// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

syntax = "proto3";

package imp.gltf;

import "core/math/math.proto";
import "core/proto/imp.proto";

// option cc_api_version = 2;
option java_package = "com.google.ar.imp.proto";

message Behavior {
  enum ValueType {
    UNKNOWN = 0;
    BOOL = 1;
    INT = 2;
    FLOAT = 3;
    FLOAT2 = 4;
    FLOAT3 = 5;
    FLOAT4 = 6;
    MAT4F = 7;
    STRING = 8;
  }

  // TODO  Add the rest of the data types defined in the glTF
  // object model spec + behavior spec.
  message Variable {
    string id = 1 [ctype = STRING_PIECE];
    ValueType type = 2;
    oneof value {
      bool value_bool = 3;
      sint32 value_int = 4;
      float value_float = 5;
      Float2 value_float2 = 6;
      Float3 value_float3 = 7;
      Float4 value_float4 = 8;
      Mat4f value_mat4f = 9;
      string value_string = 10;
    }
  }

  message Node {
    enum ConfigurationType {
      UNKNOWN = 0;
      VARIABLE = 1;
      NUMBER_OF_OUTPUT_FLOWS = 2;
      PATH = 3;
      CUSTOM_EVENT = 4;
      NODE_INDEX = 5;
      STOP_PROPAGATION = 6;
      EASING_TYPE = 7;
      EASING_DURATION = 8;
    }

    message Flow {
      string id = 1;
      uint32 node = 2;
      string socket = 3;
    }

    message Configuration {
      ConfigurationType id = 1;
      ValueType type = 2;
      oneof value {
        sint32 value_int = 3;
        string value_string = 4;
        bool value_bool = 5;
        float value_float = 6;
      }
    }

    message Value {
      oneof value {
        Variable variable = 1;
        Flow connection = 2;
      }
    }

    string type = 1;
    uint32 index = 2;
    repeated Configuration configuration = 3;
    repeated Value values = 4;
    repeated Flow flows = 5;
  }

  message CustomEvent {
    string id = 1;
    repeated Variable values = 2;
  }

  message Type {
    message BehaviorString {}
    message Extensions {
      BehaviorString behavior_string = 1 [
        json_name = "AMZN_interactivity_string",
        (imp.optional_type) = ABSL_OPTIONAL
      ];
    }
    string signature = 1;
    Extensions extensions = 2;
  }

  repeated Node nodes = 1;
  repeated Variable variables = 2;
  repeated CustomEvent custom_events = 3;
  repeated Type types = 4;
}
