// Copyright 2024 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

edition = "2024";

package com.google.ar.imp.view;

import "core/view/utils/proto/render_settings.proto";
import "core/view/utils/proto/view_config.proto";
import "java/com/google/ar/imp/view/xr/xr_setup_params.proto";

// option cc_api_version = 2;
option java_package = "com.google.ar.imp.view";

// Configurations for an ImpSurfaceView or ImpTextureView. A default instance is
// sufficient for functional rendering.
message SetupParams {
  // Configures the threading model to use with Impress.
  enum ThreadMode {
    // Impress will run on the main thread using the choreographer. In most
    // cases, this should be fine for performance since rendering is still done
    // on a background thread. However, long running work using the Impress API
    // could block the main thread. The benefit of this is that calls can be
    // made between Impress and android APIs without needing to hop between
    // threads.
    MAIN_DEFAULT = 0;
    // Impress will run on a background thread using the choreographer.
    // All calls into Impress must happen from the background thread. That means
    // that custom jni calls or calls into Impress scripting should use
    // impApi.getFrameScheduler() to execute the work on the background thread.
    BACKGROUND = 1;
  }

  string custom_native_library = 1;
  bool skip_native_library_load = 2 [default = false];
  bool is_opaque = 3 [default = true];
  int64 platform_handle = 4;
  string view_identifier = 5;
  float desired_size_scale = 6 [default = 1.0];
  ThreadMode thread_mode = 7;
  // Additional flags to be enabled when creating the backing swap chain in
  // Filament. Flags should be taken from the config constants in
  // filament/swapchain.h (e.g., filament::SwapChain::CONFIG_READABLE).
  int64 swap_chain_flags = 8 [default = 0];
  // The name of the thread that the background frame scheduler will run on.
  string background_thread_name = 9 [default = "impressThread"];
  // If true, then when the swapchain needs to be destroyed or re-created, the
  // operation wil block until it is completed. This is important to ensure that
  // the android surface used by the swapchain isn't used after it has been
  // destroyed. This only has an effect when using BACKGROUND thread_mode.
  bool use_synchronous_surface_changes = 10 [default = true];
  // The view config for the main view. Used in preference over
  // `view_render_settings` if set.
  .imp.ViewConfig view_config = 11;
  // The setup params specific for XR / OpenXR platform, such as stereoscopic
  // rendering, foveation, etc.
  xr.XrSetupParams xr_setup_params = 12;
}
