/*
 * Copyright 2024 Google LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef THIRD_PARTY_IMPRESS_CORE_VIEW_PLATFORMS_XR_ANDROID_XR_INPUT_CONTROLLER_H_
#define THIRD_PARTY_IMPRESS_CORE_VIEW_PLATFORMS_XR_ANDROID_XR_INPUT_CONTROLLER_H_

#include <cstddef>
#include <cstdint>
#include <optional>
#include <string>
#include <vector>

#include "absl/status/status.h"
#include "absl/status/statusor.h"
#include "absl/strings/string_view.h"
#include "absl/types/optional.h"
#include "core/actions/input_action_event.h"
#include "core/math/transform.h"
#include "core/view/base_view.h"
#include "core/view/platforms/xr_android/openxr_includes.h"
#include "core/view/platforms/xr_android/xr_action_config.h"
#include "core/view/platforms/xr_android/xr_action_params.proto.imp.h"
#include "core/view/platforms/xr_android/xr_session_host.h"
#include "core/view/utils/string_map.h"
#include "robin_map/include/tsl/robin_map.h"

namespace imp {

// A data-driven interface for OpenXR action system.
//
// Accepts a series of protos representing the XrActions, XrActionSets, and
// suggested bindings and makes the corresponding calls to create them in the
// OpenXR runtime. XrActionController will then send InputActionEvents,
// containing the state of every XrAction, to the InputManager every frame.
//
// The default configuration is:
//   - A single action set with name "app".
//   - "pose", "grip", "menu", and "select" input actions.
//   - Bindings for the above actions and the OpenXR Khronos Simple Controller.
//
// These default settings provide basic input and haptic support for
// applications.
//
// Custom XrActions/XrActionSets/bindings can be configured by
// calling XrActionController::AttachXrActions before
// imp::OpenXrSessionBeginEvent. This can be in
// imp::OpenXrReferenceSpaceCreatedEvent, for example. XrActionController can be
// accessed through the Registry.
//
// See https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#input for
// comprehensive documentation on OpenXR input & haptics.
class XrActionController {
 public:
  explicit XrActionController(XrSessionHost& xr_session_host);

  // Registers XrActions, suggests interaction profile bindings, and attaches
  // XrActionSets.
  //
  // As per the OpenXR spec, XrActionSets are immutable once attached.
  // https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#input
  absl::Status AttachXrActions(
      std::vector<XrActionSetParams> xr_action_set_params =
          XrActionConfig::GetDefaultXrActionSetParams(),
      std::vector<XrActionParams> xr_action_params =
          XrActionConfig::GetDefaultXrActionParams(),
      std::vector<XrActionSetBindingParams> xr_action_set_binding_params =
          XrActionConfig::GetDefaultActionSetBindingParams());

  // Corresponds to OpenXR's XrHapticVibration:
  // https://registry.khronos.org/OpenXR/specs/1.0/html/xrspec.html#XrHapticVibration
  struct ApplyHapticFeedbackOptions {
    float amplitude;  // The vibration amplitude, from 0.0 to 1.0.
    int64_t duration = XR_MIN_HAPTIC_DURATION;   // Duration, in nanoseconds.
    float frequency = XR_FREQUENCY_UNSPECIFIED;  // Vibration frequency, in Hz.
  };

  // Applies a haptic output action in OpenXR.
  // If no action_set_name is provided, there must be exactly one attached
  // action set to use as a default.
  absl::Status ApplyHapticFeedback(
      ApplyHapticFeedbackOptions options, absl::string_view subaction_path,
      std::optional<absl::string_view> action_set_name = std::nullopt,
      absl::string_view action_name = kDefaultHapticActionName);

  // Stops a haptic output action in OpenXR.
  // If no action_set_name is provided, there must be exactly one attached
  // action set to use as a default.
  absl::Status StopHapticFeedback(
      absl::string_view subaction_path,
      std::optional<absl::string_view> action_set_name = std::nullopt,
      absl::string_view action_name = kDefaultHapticActionName);

  // Based on this setting, XrActionController may attach the default actions,
  // action sets, and bindings specified in XrActionConfig.
  enum class XrSessionActionConfig {
    kUseXrActionDefaults,
    kOmitXrActionDefaults,
  };

  void SetXrSessionActionConfig(XrSessionActionConfig xr_session_action_config);

  // Data generated by XrActionController may be processed by default. When
  // actions are attached, a new ControllerInputHandler may be constructed with
  // default settings or omitted based on this setting.
  enum class InputHandlerConfig {
    kCreateDefaultControllerInputHandler,
    kOmitDefaultControllerInputHandler,
  };

  // Sets the configuration for creating a complementary InputHandler.
  void SetInputHandlerConfig(InputHandlerConfig input_handler_config);

 private:
  // Registers XrActions, suggests interaction profile bindings, and
  // attaches XrActionSets. Uses XrActionConfig defaults.
  void AttachDefaultXrActions();

  // Sends one InputActionEvent per XrActionSet to InputManager.
  absl::Status OnFocusedWaitFrame();

  // A struct to reference the XrAction and parameters after it has been
  // created in const the OpenXR runtime.
  struct XrActionReference {
    XrActionParams xr_action_params;
    XrAction xr_action_handle = XR_NULL_HANDLE;
    // Pose(aka Transform<float>) input actions will need one XrSpace per
    // subaction_path.
    tsl::robin_map<XrPath, XrSpace> xr_subaction_path_to_xr_action_space;
    tsl::robin_map<XrPath, std::string> xr_subaction_path_to_subaction_path;

    // Pre-computes the hash of the action name for faster lookups.
    size_t action_name_hash;
  };

  // Builds an XrActionStateGetInfo.
  absl::StatusOr<XrActionStateGetInfo> BuildXrActionStateGetInfo(
      const XrActionReference& xr_action_reference, XrPath xr_subaction_path);

  // A struct used to reference the XrActionSet and parameters after it has
  // been created in the OpenXR runtime.
  struct XrActionSetReference {
    XrActionSetParams xr_action_set_params;
    XrActionSet xr_action_set_handle = XR_NULL_HANDLE;
    tsl::robin_map<XrAction, XrActionReference>
        xr_action_to_xr_action_reference;

    // Cache the InputActionEvent and map to avoid reallocating
    // storage every frame.
    StringMap<XrAction> action_name_to_xr_action;
    tsl::robin_map<XrPath, InputActionEvent>
        xr_subaction_path_to_input_action_event;
  };

  // Registers an XrActionSet with OpenXR.
  absl::StatusOr<XrActionSet> SetupXrActionSet(
      XrActionSetParams xr_action_set_params);

  // Registers a single XrAction.
  absl::Status SetupXrAction(XrActionParams xr_action_params);

  // Configures bindings in OpenXR.
  absl::Status SetupXrActionSetBindings(
      XrActionSetBindingParams xr_action_set_binding_params);

  // Syncs the state of all XrActions in a referenced XrActionSet. For each
  // subaction path, an InputActionEvent is sent to the InputManager.
  absl::Status SyncXrActionSetState(
      XrActionSetReference& xr_action_set_reference);

  // Returns an InputActionState which contains the information retrieved from
  // an xrGetActionState* OpenXR call.
  template <typename T>
  absl::StatusOr<InputActionState<T>> FetchInputActionState(
      const XrActionReference& xr_action_reference, XrPath xr_subaction_path);

  // Fetches state for a Transform<float> input action, which involves notably
  // involves syncing the XrSpace.
  inline absl::StatusOr<std::optional<InputActionState<Transform<float>>>>
  FetchTransformInputActionState(const XrActionReference& xr_action_reference,
                                 XrPath xr_subaction_path);

  absl::StatusOr<XrHapticActionInfo> BuildXrHapticActionInfo(
      absl::string_view subaction_path,
      std::optional<absl::string_view> action_set_name = std::nullopt,
      absl::string_view action_name = kDefaultHapticActionName);

  BaseView* view_;
  const XrSessionHost& xr_session_host_;
  StringMap<XrActionSetReference> action_set_name_to_xr_action_set_reference_;
  bool have_action_sets_been_attached_ = false;
  XrSessionActionConfig xr_session_action_config_ =
      XrSessionActionConfig::kUseXrActionDefaults;
  InputHandlerConfig input_handler_config_ =
      InputHandlerConfig::kCreateDefaultControllerInputHandler;
};
}  // namespace imp

#endif  // THIRD_PARTY_IMPRESS_CORE_INPUT_XR_INPUT_CONTROLLER_H_
